/**
 *  Copyright (c) 2007-2010 CyberInfrastructure and Geospatial
 *  Information Laboratory (CIGI), University of Illinois at
 *  Urbana-Champaign, All Rights Reserved.
 */

// This file was auto-generated by SimpleGrid SkeletonGen utility
// Built on : Apr 7, 2011
package org.simplegrid.app.testapp;

public class TESTAPPSkeleton implements TESTAPPSkeletonInterface {
	public org.simplegrid.app.testapp.GetResultResponse getResult
	(org.simplegrid.app.testapp.GetResult getResult0)
	{
		org.simplegrid.app.testapp.TESTAPP testapp0= new org.simplegrid.app.testapp.TESTAPP();
		java.lang.String r = testapp0.getResult(getResult0.getArgs0(), getResult0.getArgs1(), getResult0.getArgs2());
		org.simplegrid.app.testapp.GetResultResponse res = new org.simplegrid.app.testapp.GetResultResponse();
		res.set_return(r);
		return res;
	}

	public org.simplegrid.app.testapp.SubmitResponse submit
	(org.simplegrid.app.testapp.Submit submit1)
	{
		org.simplegrid.app.testapp.TESTAPP testapp1= new org.simplegrid.app.testapp.TESTAPP();
		java.lang.String r = testapp1.submit(submit1.getArgs0(), submit1.getArgs1());
		org.simplegrid.app.testapp.SubmitResponse res = new org.simplegrid.app.testapp.SubmitResponse();
		res.set_return(r);
		return res;
	}

	public org.simplegrid.app.testapp.GetStatusResponse getStatus
	(org.simplegrid.app.testapp.GetStatus getStatus2)
	{
		org.simplegrid.app.testapp.TESTAPP testapp2= new org.simplegrid.app.testapp.TESTAPP();
		java.lang.String r = testapp2.getStatus(getStatus2.getArgs0());
		org.simplegrid.app.testapp.GetStatusResponse res = new org.simplegrid.app.testapp.GetStatusResponse();
		res.set_return(r);
		return res;
	}

}
